name: JUnit Pioneer Site

on:
  push:
    branches: [ grandmaster, site-source ]
  repository_dispatch:
    types: [triggerSiteBuild]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          ref: 'grandmaster'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'temurin'
          cache: 'gradle'

      - name: Print versions
        run: |
          ruby -v
          bundler -v
          java -version

      - name: Gradle setup, build and push
        uses: gradle/gradle-build-action@v2
        with:
          arguments: setup buildSite pushSite --no-daemon --stacktrace
